services:
  - type: web
    name: travel-planner
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn test:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SERPAPI_KEY
        fromService:
          name: serpapi
          type: secret
      - key: OPENAI_API_KEY
        fromService:
          name: openai
          type: secret
    healthCheckPath: /docs 