services:
  - type: web
    name: travel-assistant-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn test:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 8000
      - key: OPENAI_API_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
    healthCheckPath: /docs 